name: Run Python Script

on:
  schedule:
   - cron: "0,10,20,30,40,50 * * * *"  # Чётко каждые 10 минут  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Ensure directory exists
        run: mkdir -p $(dirname csv/all_ad.csv)

      - name: Run script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID_VICTOR: ${{ secrets.TELEGRAM_CHAT_ID_VICTOR }}
          TELEGRAM_CHAT_ID_ANTON: ${{ secrets.TELEGRAM_CHAT_ID_ANTON }}
          TELEGRAM_CHAT_ID_IRINA: ${{ secrets.TELEGRAM_CHAT_ID_IRINA }}
          TELEGRAM_CHAT_ID_VICTORIA: ${{ secrets.TELEGRAM_CHAT_ID_VICTORIA }}
        run: python main.py


      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add csv/all_ad.csv
          git commit -m "Update CSV file with new ads" || echo "No changes to commit"
          git push
