name: Run Python Script

on:
  schedule:
    - cron: "*/10 * * * *"  
  workflow_dispatch: 
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Ensure directory exists
        run: mkdir -p $(dirname csv/all_ad.csv)

      - name: Check file write permissions
        run: |
          touch csv/all_ad.csv
          echo "Write test" >> csv/all_ad.csv
          cat csv/all_ad.csv

      - name: Run script
        run: python main.py
